---
- name: Update the cache
  apt: 
    update_cache: true

- name: adding the mongodb repository 
  apt_repository:
    repo: deb {{ VERSION_3_4_URL }} multiverse
    state: present
  register: apt_repository
