---
- name: Download Spark
  get_url: 
    url: "{{ SPARK_URL }}"
    dest: /tmp
  register: download
 
- name: Unarchiving spark 
  unarchive: 
    src: "/tmp/spark-{{ SPARK_VERSION }}-bin-hadoop2.7.tgz"
    dest: /tmp
    remote_src: true

- name: Checking if spark home is present
  stat:
    path: "{{ SPARK_HOME }}"
  register: spark_home_status

- name: Renaming the spark directory
  command: "mv /tmp/spark-{{ SPARK_VERSION }}-bin-hadoop2.7 {{ SPARK_HOME }}"
  when: spark_home_status.stat.exists == false


- name: Changing the owner to spark 
  file:
    path: "{{ SPARK_HOME }}"
    state: directory
    owner: "{{ SPARK_USER }}"
    group: "{{ SPARK_GROUP }}"
    recurse: yes  
 

