---
- name: Stop spark master
  command: "{{ SPARK_HOME }}/sbin/stop-master.sh"
  when: inventory_hostname in groups['masters']
  become: true
  become_user: "{{ SPARK_USER }}"

- name: Start spark master
  command: "{{ SPARK_HOME }}/sbin/start-master.sh"
  when: inventory_hostname in groups['masters']
  become: true
  become_user: "{{ SPARK_USER }}"

- name: Stop spark slave
  command: "{{ SPARK_HOME }}/sbin/stop-slave.sh"
  when: inventory_hostname in groups['slaves']
  become: true
  become_user: "{{ SPARK_USER }}"

- name: Start spark slave
  command: "{{ SPARK_HOME }}/sbin/start-slave.sh spark://{{ SPARK_MASTER_HOST }}:{{ SPARK_MASTER_PORT }}"
  when: inventory_hostname in groups['slaves']
  become: true
  become_user: "{{ SPARK_USER }}"

