---
- name: Create log dir if missing
  file: state=directory recurse=yes dest={{ mongodb_systemlog_path|dirname }} owner={{ mongodb_user }} group={{mongodb_user}} mode=0755

- name: Check than logfile exists
  stat: path={{ mongodb_systemlog_path }}
  register: logfile_stat

- name: Create log if missing
  file: state=touch dest={{ mongodb_systemlog_path }} owner={{ mongodb_user }} group={{mongodb_user}} mode=0755
  when: logfile_stat is defined and not logfile_stat.stat.exists

- name: Ensure dbpath directory
  file:
    path: "{{ mongodb_storage_dbpath }}"
    state: directory
    owner: "{{ mongodb_user }}"
    recurse: yes

