---
- name: copying slaves template
  template:
    src: slaves.j2
    dest: "{{ SPARK_HOME }}/conf/slaves"

- name: copying spark-env.sh template
  template:
    src: spark-env.sh.j2 
    dest: "{{ SPARK_HOME }}/conf/spark-env.sh"
